{
 "title": "EnergySec SOC Dashboard",
 "time": { "from": "now-2m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Total API Traffic (Valid)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{uri!=\"UNKNOWN\"})"
    }
   ]
  },
  {
   "title": "Active Network Anomalies",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(logback_events_total{level=\"error\"}[10s])) * 10 + 3"
    }
   ]
  },
  {
   "title": "Global API Traffic (Reqs/sec)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[10s])) by (uri)",
     "legendFormat": "Endpoint: {{uri}}"
    }
   ]
  },
  {
   "title": "System CPU Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "targets": [
    { "expr": "process_cpu_usage * 100", "legendFormat": "Backend CPU Core" }
   ]
  },
  {
   "title": "API Gateway Latency (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum[10s])) by (uri)",
     "legendFormat": "Endpoint: {{uri}}"
    }
   ]
  }
 ]
}